# Generated by Django 4.1.7 on 2023-03-28 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AbilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about_me', models.TextField()),
                ('biography', models.TextField()),
                ('abilitytype', models.ManyToManyField(through='myapp.Ability', to='myapp.abilitytype')),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hero1', to='myapp.hero')),
                ('hero2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hero2', to='myapp.hero')),
                ('relationshipType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.relationshiptypes')),
            ],
        ),
        migrations.AddField(
            model_name='ability',
            name='abilitytype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.abilitytype'),
        ),
        migrations.AddField(
            model_name='ability',
            name='heroes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.hero'),
        ),
    ]
